### ISSUE TITLE
Request for Usage Instructions

### ISSUE THREAD

**Issue by noblesocius** [denisdenisi4/Topaz#1]
Hii @devaskim,
Could you please add some instructions to the README.md file on using this wrapper? 
My scenario is that I have a Topaz signature pad and I'd like to get the signature from it to my web application that is hosted on Linux. Do you think that this would be possible if I make use of this wrapper? Thank you

**Comment by devaskim** [comment]
Hi @noblesocius ,
This repo was for integration with the device that mixes paints. It is not for signature pad or somethings similar.
As I remember, you need just open this repo in Visual Studio Community.

**Comment by noblesocius** [comment]
Oh. My bad. There's a company called Topaz that makes signature pads and they only provide SDKs in C++. Thought this was a wrapper for that. Thanks for the reply. Appreciate it

**Comment by devaskim** [comment]
@noblesocius 
The most and single valuable part is `topaz.i`. It is wrapper interface for C++ lib that is being used by [SWIG ](https://www.swig.org/Doc3.0/Python.html#Python_nn2)tool.
